// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Latest_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ILatest_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaLatest_Detail0 property.
        /// </summary>
		bool HasNextpanoramaLatest_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaLatest_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaLatest_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechLatest_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechLatest_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareLatest_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareLatest_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartLatest_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartLatest_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceLatest_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceLatest_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaLatest_Detail0 command.
        /// </summary>
		ICommand NextpanoramaLatest_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaLatest_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaLatest_Detail0 { get; }

	}
}
