// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Mostpopular_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMostpopular_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the Mostpopular_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Mostpopular_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedMostpopular_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedMostpopular_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Latest_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Latest_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedLatest_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedLatest_NewsListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the RefreshMostpopular_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshMostpopular_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetMostpopular_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand GetMostpopular_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the RefreshLatest_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand RefreshLatest_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the GetLatest_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand GetLatest_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
