// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Mostpopular_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMostpopular_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaMostpopular_Detail0 property.
        /// </summary>
		bool HasNextpanoramaMostpopular_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaMostpopular_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaMostpopular_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechMostpopular_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechMostpopular_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareMostpopular_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareMostpopular_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartMostpopular_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartMostpopular_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceMostpopular_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceMostpopular_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaMostpopular_Detail0 command.
        /// </summary>
		ICommand NextpanoramaMostpopular_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaMostpopular_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaMostpopular_Detail0 { get; }

	}
}
