// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Latest_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Latest_DetailViewModel : ViewModelsBase.VMBase, IViewModels.ILatest_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.Latest_LatestRss _latest_LatestRss;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Latest_DetailViewModel" /> class.
        /// </summary>
        /// <param name="latest_LatestRss">The Latest_ Latest Rss.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Latest_DetailViewModel(Repositories.Latest_LatestRss latest_LatestRss, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_latest_LatestRss = latest_LatestRss;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaLatest_Detail0;

        /// <summary>
        /// HasNextpanoramaLatest_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaLatest_Detail0
        {
            get
            {
				return _hasNextpanoramaLatest_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaLatest_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaLatest_Detail0;

        /// <summary>
        /// HasPreviouspanoramaLatest_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaLatest_Detail0
        {
            get
            {
				return _hasPreviouspanoramaLatest_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaLatest_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechLatest_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechLatest_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechLatest_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechLatest_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechLatest_DetailStaticControlCommand
        {
            get { return _textToSpeechLatest_DetailStaticControlCommand = _textToSpeechLatest_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechLatest_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareLatest_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareLatest_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareLatest_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareLatest_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareLatest_DetailStaticControlCommand
        {
            get { return _shareLatest_DetailStaticControlCommand = _shareLatest_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareLatest_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartLatest_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartLatest_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.ILatest_DetailViewModel), CreateTileInfoLatest_DetailStaticControl());
        }
		

        private ICommand _pinToStartLatest_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartLatest_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartLatest_DetailStaticControlCommand
        {
            get { return _pinToStartLatest_DetailStaticControlCommand = _pinToStartLatest_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartLatest_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceLatest_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceLatest_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceLatest_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceLatest_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceLatest_DetailStaticControlCommand
        {
            get { return _goToSourceLatest_DetailStaticControlCommand = _goToSourceLatest_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceLatest_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaLatest_Detail0 command.
        /// </summary>
        public async void NextpanoramaLatest_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _latest_LatestRss.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaLatest_Detail0;

        /// <summary>
        /// Gets the NextpanoramaLatest_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaLatest_Detail0
        {
            get { return _nextpanoramaLatest_Detail0 = _nextpanoramaLatest_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaLatest_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaLatest_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaLatest_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _latest_LatestRss.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaLatest_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaLatest_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaLatest_Detail0
        {
            get { return _previouspanoramaLatest_Detail0 = _previouspanoramaLatest_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaLatest_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaLatest_Detail0 = await _latest_LatestRss.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaLatest_Detail0 = await _latest_LatestRss.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Latest_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoLatest_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-f39fee7d-1a66-4561-bec7-3ef3fde95aee.png"
            };
            return tileInfo;
        }
    }
}
