// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Mostpopular_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Mostpopular_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IMostpopular_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.Mostpopular_MainFeedRss _mostpopular_MainFeedRss;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Mostpopular_DetailViewModel" /> class.
        /// </summary>
        /// <param name="mostpopular_MainFeedRss">The Mostpopular_ Main Feed Rss.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Mostpopular_DetailViewModel(Repositories.Mostpopular_MainFeedRss mostpopular_MainFeedRss, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_mostpopular_MainFeedRss = mostpopular_MainFeedRss;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaMostpopular_Detail0;

        /// <summary>
        /// HasNextpanoramaMostpopular_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaMostpopular_Detail0
        {
            get
            {
				return _hasNextpanoramaMostpopular_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaMostpopular_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaMostpopular_Detail0;

        /// <summary>
        /// HasPreviouspanoramaMostpopular_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaMostpopular_Detail0
        {
            get
            {
				return _hasPreviouspanoramaMostpopular_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaMostpopular_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechMostpopular_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechMostpopular_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechMostpopular_DetailStaticControlCommand
        {
            get { return _textToSpeechMostpopular_DetailStaticControlCommand = _textToSpeechMostpopular_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechMostpopular_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareMostpopular_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareMostpopular_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareMostpopular_DetailStaticControlCommand
        {
            get { return _shareMostpopular_DetailStaticControlCommand = _shareMostpopular_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareMostpopular_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartMostpopular_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IMostpopular_DetailViewModel), CreateTileInfoMostpopular_DetailStaticControl());
        }
		

        private ICommand _pinToStartMostpopular_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartMostpopular_DetailStaticControlCommand
        {
            get { return _pinToStartMostpopular_DetailStaticControlCommand = _pinToStartMostpopular_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartMostpopular_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceMostpopular_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceMostpopular_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceMostpopular_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceMostpopular_DetailStaticControlCommand
        {
            get { return _goToSourceMostpopular_DetailStaticControlCommand = _goToSourceMostpopular_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceMostpopular_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaMostpopular_Detail0 command.
        /// </summary>
        public async void NextpanoramaMostpopular_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _mostpopular_MainFeedRss.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaMostpopular_Detail0;

        /// <summary>
        /// Gets the NextpanoramaMostpopular_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaMostpopular_Detail0
        {
            get { return _nextpanoramaMostpopular_Detail0 = _nextpanoramaMostpopular_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaMostpopular_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaMostpopular_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaMostpopular_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _mostpopular_MainFeedRss.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaMostpopular_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaMostpopular_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaMostpopular_Detail0
        {
            get { return _previouspanoramaMostpopular_Detail0 = _previouspanoramaMostpopular_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaMostpopular_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaMostpopular_Detail0 = await _mostpopular_MainFeedRss.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaMostpopular_Detail0 = await _mostpopular_MainFeedRss.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Mostpopular_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoMostpopular_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-5b225b1a-58cc-4c2c-908e-3bd49db8b144.png"
            };
            return tileInfo;
        }
    }
}
